### ISSUE TITLE
Molecule login not working

### ISSUE THREAD

**Issue by jseguillon** [ansible-community/molecule-kubevirt#32]
No idea why but .. 

```
 molecule login --host instance -s kubevirt  
```

results
```
INFO     Running kubevirt > login
Traceback (most recent call last):
  File "xxx/.tox/py39-ansible_4/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "xxx/.tox/py39-ansible_4/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "xxx/.tox/py39-ansible_4/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "xxx/.tox/py39-ansible_4/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "xxx/.tox/py39-ansible_4/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "xxx/.tox/py39-ansible_4/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "xxx/.tox/py39-ansible_4/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "xxx/.tox/py39-ansible_4/lib/python3.9/site-packages/molecule/command/login.py", line 166, in login
    base.execute_subcommand(scenario.config, subcommand)
  File "xxx/.tox/py39-ansible_4/lib/python3.9/site-packages/molecule/command/base.py", line 149, in execute_subcommand
    return command(config).execute()
  File "xxx/.tox/py39-ansible_4/lib/python3.9/site-packages/molecule/logger.py", line 188, in wrapper
    rt = func(*args, **kwargs)
  File "xxx/.tox/py39-ansible_4/lib/python3.9/site-packages/molecule/command/login.py", line 101, in execute
    self._get_login(hostname)
  File "xxx/.tox/py39-ansible_4/lib/python3.9/site-packages/molecule/command/login.py", line 146, in _get_login
    app.runtime.exec(cmd)
  File "xxx/.tox/py39-ansible_4/lib/python3.9/site-packages/ansible_compat/runtime.py", line 138, in exec
    result = run_func(
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/env ssh 10.96.232.151 -l molecule -p 22 -i /home/jseguillon/.cache/molecule/molecule_kubevirt/kubevirt/identity_instance -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no'

```

**Comment by jseguillon** [comment]
Not a problem with this driver: it's a regression from molecule. 

https://github.com/ansible-community/molecule/issues/3435

**Comment by jseguillon** [comment]
In case of need : downgrade to 3.5.2

**Comment by jseguillon** [comment]
now OK with molecule 4.0.0
